object BlockDataHelper {

    fun isClickable(block: String): Boolean {
        return when(block) {
            "NOTE_BLOCK" -> true
            "CHEST" -> true
            "ENDER_CHEST" -> true
            "TRAPPED_CHEST" -> true
            "CRAFTING_TABLE" -> true
            "CRAFTER" -> true
            "FURNACE" -> true
            "BLAST_FURNACE" -> true
            "SMOKER" -> true
            "ENCHANTING_TABLE" -> true
            "ANVIL" -> true
            "CHIPPED_ANVIL" -> true
            "DAMAGED_ANVIL" -> true
            "BREWING_STAND" -> true
            "CAULDRON" -> true
            "BELL" -> true
            "COMPOSTER" -> true
            "LOOM" -> true
            "STONECUTTER" -> true
            "GRINDSTONE" -> true
            "BARREL" -> true
            "SMITHING_TABLE" -> true
            "FLETCHING_TABLE" -> true
            "CARTOGRAPHY_TABLE" -> true
            "LECTERN" -> true
            "JUKEBOX" -> true
            "BEEHIVE" -> true
            "BEE_NEST" -> true
            "DAYLIGHT_DETECTOR" -> true
            "END_PORTAL_FRAME" -> true
            "LEVER" -> true
            "LIGHT_WEIGHTED_PRESSURE_PLATE" -> true
            "HEAVY_WEIGHTED_PRESSURE_PLATE" -> true
            "STONE_PRESSURE_PLATE" -> true
            "OAK_PRESSURE_PLATE" -> true
            "SPRUCE_PRESSURE_PLATE" -> true
            "BIRCH_PRESSURE_PLATE" -> true
            "JUNGLE_PRESSURE_PLATE" -> true
            "ACACIA_PRESSURE_PLATE" -> true
            "DARK_OAK_PRESSURE_PLATE" -> true
            "REDSTONE_BLOCK" -> true
            "OAK_BUTTON" -> true
            "SPRUCE_BUTTON" -> true
            "BIRCH_BUTTON" -> true
            "JUNGLE_BUTTON" -> true
            "ACACIA_BUTTON" -> true
            "DARK_OAK_BUTTON" -> true
            "STONE_BUTTON" -> true
            "TRIPWIRE_HOOK" -> true
            "REDSTONE_LAMP" -> true
            "COMPARATOR" -> true
            "REPEATER" -> true
            "DAYLIGHT_DETECTOR" -> true
            "REDSTONE_TORCH" -> true
            "REDSTONE_WALL_TORCH" -> true
            "TNT" -> true
            "TRAPPED_CHEST" -> true
            "DISPENSER" -> true
            "DROPPER" -> true
            "HOPPER" -> true
            "NOTE_BLOCK" -> true
            "STICKY_PISTON" -> true
            "PISTON" -> true
            "MOVING_PISTON" -> true
            "OBSERVER" -> true
            "REDSTONE_WIRE" -> true
            "TRIPWIRE" -> true
            "COMPARATOR" -> true
            "REPEATER" -> true
            "COMPARATOR" -> true
            "DETECTOR_RAIL" -> true
            "ACTIVATOR_RAIL" -> true
            "POWERED_RAIL" -> true
            "RAIL" -> true
            "LEVER" -> true
            "TRIPWIRE_HOOK" -> true
            "DAYLIGHT_DETECTOR" -> true
            "STONE_BUTTON" -> true
            "STONE_PRESSURE_PLATE" -> true
            "HEAVY_WEIGHTED_PRESSURE_PLATE" -> true
            "LIGHT_WEIGHTED_PRESSURE_PLATE" -> true
            "REDSTONE_TORCH" -> true
            "REDSTONE_WALL_TORCH" -> true
            "REDSTONE_LAMP" -> true
            "NOTE_BLOCK" -> true
            "JUKEBOX" -> true
            "DISPENSER" -> true
            "DROPPER" -> true
            "OBSERVER" -> true
            "PISTON" -> true
            "STICKY_PISTON" -> true
            "HOPPER" -> true
            "BEACON" -> true
            "CHEST" -> true
            "TRAPPED_CHEST" -> true
            "ENDER_CHEST" -> true
            "CAULDRON" -> true
            "BREWING_STAND" -> true
            "ENCHANTING_TABLE" -> true
            "ANVIL" -> true
            "CHIPPED_ANVIL" -> true
            "DAMAGED_ANVIL" -> true
            "GRINDSTONE" -> true
            "STONECUTTER" -> true
            "SMOKER" -> true
            "BLAST_FURNACE" -> true
            "FURNACE" -> true
            "BARREL" -> true
            "BELL" -> true
            "CARTOGRAPHY_TABLE" -> true
            "COMPOSTER" -> true
            "FLETCHING_TABLE" -> true
            "LOOM" -> true
            "SMITHING_TABLE" -> true
            "LECTERN" -> true
            "GRINDSTONE" -> true
            "BEEHIVE" -> true
            "BEE_NEST" -> true
            "RESPAWN_ANCHOR" -> true
            "OAK_BUTTON" -> true
            "SPRUCE_BUTTON" -> true
            "BIRCH_BUTTON" -> true
            "JUNGLE_BUTTON" -> true
            "ACACIA_BUTTON" -> true
            "DARK_OAK_BUTTON" -> true
            "CRIMSON_BUTTON" -> true
            "WARPED_BUTTON" -> true
            "MANGROVE_BUTTON" -> true
            "BAMBOO_BUTTON" -> true
            "CHERRY_BUTTON" -> true
            "OAK_PRESSURE_PLATE" -> true
            "SPRUCE_PRESSURE_PLATE" -> true
            "BIRCH_PRESSURE_PLATE" -> true
            "JUNGLE_PRESSURE_PLATE" -> true
            "ACACIA_PRESSURE_PLATE" -> true
            "DARK_OAK_PRESSURE_PLATE" -> true
            "CRIMSON_PRESSURE_PLATE" -> true
            "WARPED_PRESSURE_PLATE" -> true
            "MANGROVE_PRESSURE_PLATE" -> true
            "BAMBOO_PRESSURE_PLATE" -> true
            "CHERRY_PRESSURE_PLATE" -> true
            "OAK_DOOR" -> true
            "SPRUCE_DOOR" -> true
            "BIRCH_DOOR" -> true
            "JUNGLE_DOOR" -> true
            "ACACIA_DOOR" -> true
            "DARK_OAK_DOOR" -> true
            "CRIMSON_DOOR" -> true
            "WARPED_DOOR" -> true
            "MANGROVE_DOOR" -> true
            "BAMBOO_DOOR" -> true
            "CHERRY_DOOR" -> true
            "OAK_TRAPDOOR" -> true
            "SPRUCE_TRAPDOOR" -> true
            "BIRCH_TRAPDOOR" -> true
            "JUNGLE_TRAPDOOR" -> true
            "ACACIA_TRAPDOOR" -> true
            "DARK_OAK_TRAPDOOR" -> true
            "CRIMSON_TRAPDOOR" -> true
            "WARPED_TRAPDOOR" -> true
            "MANGROVE_TRAPDOOR" -> true
            "BAMBOO_TRAPDOOR" -> true
            "CHERRY_TRAPDOOR" -> true
            "OAK_FENCE_GATE" -> true
            "SPRUCE_FENCE_GATE" -> true
            "BIRCH_FENCE_GATE" -> true
            "JUNGLE_FENCE_GATE" -> true
            "ACACIA_FENCE_GATE" -> true
            "DARK_OAK_FENCE_GATE" -> true
            "CRIMSON_FENCE_GATE" -> true
            "WARPED_FENCE_GATE" -> true
            "MANGROVE_FENCE_GATE" -> true
            "BAMBOO_FENCE_GATE" -> true
            "CHERRY_FENCE_GATE" -> true
            else -> false
        }
    }
}